defmodule Mokaid.AI.Workers.ConverseWorker do
  @moduledoc """
  Conversational replies: when a teammate writes in a task thread while the
  assigned agent is NOT running, the agent still answers — the thread is a
  real conversation, not a log. The reply is generated by the AI worker
  (which posts it back as a task comment through the worker API).
  """

  use Oban.Worker, queue: :ai_dispatch, max_attempts: 2

  alias Mokaid.AI
  alias Mokaid.Tasks

  @impl Oban.Worker
  def perform(%Oban.Job{args: %{"workspace_id" => workspace_id, "task_id" => task_id}}) do
    config = Application.fetch_env!(:mokaid, :ai_worker)
    task = Tasks.get_task(workspace_id, task_id)

    cond do
      task == nil or task.assigned_agent_id == nil ->
        :ok

      # A live run already talks in the thread (ack, failure explanations);
      # don't have two voices at once.
      Tasks.active_runs_for_task(workspace_id, task_id) != [] ->
        :ok

      true ->
        payload = %{
          workspace_id: workspace_id,
          task_id: task_id,
          agent_id: task.assigned_agent_id,
          task_title: task.title,
          task_description: task.description,
          task_status: task.status,
          conversation: AI.default_input(task)["conversation"]
        }

        case config[:dispatch] do
          :sqs ->
            config[:sqs_queue_url]
            |> ExAws.SQS.send_message(Jason.encode!(Map.put(payload, :type, "converse")))
            |> ExAws.request()

            :ok

          _http ->
            case Req.post(
                   url: "#{config[:url]}/converse",
                   json: payload,
                   headers: [{"authorization", "Bearer #{config[:token]}"}],
                   receive_timeout: 30_000,
                   retry: false
                 ) do
              {:ok, %{status: status}} when status in 200..299 -> :ok
              # The reply is a nicety — never crash/retry loops over it.
              _ -> :ok
            end
        end
    end
  end
end
